services:

simple-apps:
  build: .
  image: kidx13/simple-apps
  container_name: ct-apps
  restart: always
  ports:
      - 80:3000
  volumes:
      - app-data:/app/public/images

volumes:
  app-data:
  
